### ISSUE TITLE
Document AES GCM symmetric JWE?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tekul/jose-jwt#9] opened 2016-01-04 15:04 UTC
I'm probably not getting the API properly, but the following fails with:

```
Left (KeyError "cipher initialization failed")
new-template-exe: src/Lib.hs:28:7-30: Irrefutable pattern failed for pattern Right (Jwt jwt)
```

Maybe an example could be added to the docs for this?

```haskell
{-# LANGUAGE OverloadedStrings,TemplateHaskell #-}
{-# LANGUAGE QuasiQuotes #-}
module Lib
    ( someFunc
    ) where

import           Crypto.Random
import qualified Data.Aeson        as A
import           Data.Aeson.QQ
import qualified Data.ByteString.Char8   as B
import           Jose.Jwa
import           Jose.Jwe
import           Jose.Jwk
import           Jose.Jwt

someFunc :: IO ()
someFunc = do
  let keyj = [aesonQQ|
    {"kty": "oct",
     "k":"AyM1SysPpbyDfgZld3umj1qzKObwVMkoqQ-EstJQLr_T-1qS0gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr1Z9CAow",
     "kid":"HMAC key used in JWS A.1 example"
    }
    |]
  g <- drgNew
  let A.Success key = A.fromJSON keyj :: A.Result Jwk
  let (result, g') = withDRG g (jwkEncode A128KW A128GCM key (Claims "secret claims"))
  putStrLn $ show result
  let Right (Jwt jwt) = result
  B.putStrLn jwt
  return ()
```

**Comment by tekul** [comment] 2016-01-04 16:20
You are trying to use the key from an HMAC example with AES, which won't work in this case since it's not a valid length. So cryptonite [returns an error](https://github.com/haskell-crypto/cryptonite/blob/cryptonite-v0.10/Crypto/Cipher/AES/Primitive.hs#L163). The choice of AESGCM doesn't matter here, since the key for that algorithm is generated internally. The key you supply here is the keywrap key which is used to encrypt the content key.

I think the best thing here would be to try and improve the error message, perhaps by adding a check for that specific cryptonite error.

Also, if you're posting a sample to reproduce an issue, please include the imports and pragmas, so I can run it immediately :-).

**Comment by alexanderkjeldaas** [comment] 2016-01-05 10:50
Fixed the example.

**Comment by tekul** [comment] 2016-09-21 20:22
Closing since keywrap now gives a specific error message for invalid key lengths and no further follow up.

**Closed by tekul** 2016-09-21 20:22 UTC
